language: python
python:
    - "3.5"
    - "3.6"
    - "3.7-dev"
install:
    - pip install opencv-python numpy
    - pip install pytest pytest-mock pytest-cov
    - pip install codecov
script:
    - pytest --cov
after_success:
    - codecov